# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [7]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [10]:
print(np.version.version)
print(np.__config__.show())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dilan/anaconda3/envs/Strive_School_AI_March_2021\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dilan/anaconda3/envs/Strive_School_AI_March_2021\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dilan/anaconda3/envs/Strive_School_AI_March_2021\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dilan/anaconda3/envs/Strive_School_AI_March_2021\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dilan/anaconda3/envs/Strive_School_AI_March_2021\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dilan/anaconda3/envs/Strive_School_AI_March_2021\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dilan/anaco

#### 3. Create a null vector of size 10 (★☆☆)

In [45]:
a = np.zeros(10, dtype='int8')
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

#### 4.  How to find the memory size of any array (★☆☆)

In [46]:
a.nbytes

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

![image]("./numpyadd.png")

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [49]:
b = a.copy()
b[4] = 1
b

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8)

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [28]:
np.arange(11,50)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [51]:
to_rvrs = np.array([1,2,3,4,5])
to_rvrs = to_rvrs[::-1]
to_rvrs

array([5, 4, 3, 2, 1])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [56]:
a_vec = np.arange(0,9)
a_mat = a_vec.reshape((3,3))
print(a_vec)
a_mat

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [32]:
find_zero = np.array([1,2,0,0,4,0])
non_zero = find_zero != 0
non_zero

array([ True,  True, False, False,  True, False])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [38]:
np.random.randint(10,size =(3,3,3))

array([[[0, 9, 3],
        [6, 2, 8],
        [6, 4, 4]],

       [[4, 8, 7],
        [8, 7, 0],
        [2, 8, 3]],

       [[2, 5, 6],
        [3, 6, 9],
        [5, 8, 9]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [62]:
min_max_arr = np.random.rand(10,10)
print(min_max_arr)
print(min_max_arr.min())
print(min_max_arr.max())

[[0.42015816 0.11708927 0.26297574 0.68594268 0.76843282 0.21657309
  0.01325373 0.26697156 0.57514458 0.32636877]
 [0.74062021 0.5284329  0.12066048 0.0252757  0.6956156  0.02390768
  0.98140241 0.02531004 0.41880928 0.85289951]
 [0.53327984 0.53980667 0.46427165 0.30351043 0.59047837 0.98579745
  0.16890454 0.38565957 0.45630035 0.56189505]
 [0.94316899 0.08573959 0.07839279 0.49883171 0.25106861 0.74642259
  0.4526835  0.96816298 0.19368269 0.53685625]
 [0.40015036 0.15414517 0.82901727 0.94229901 0.42086521 0.45619242
  0.32155845 0.13960103 0.6366711  0.5674117 ]
 [0.63375727 0.92373432 0.73158565 0.23597204 0.70480789 0.16109978
  0.55177638 0.35881962 0.3140383  0.13030819]
 [0.8118289  0.8185986  0.1218625  0.2725942  0.52702804 0.83380479
  0.64096556 0.68980679 0.30506199 0.15063435]
 [0.57194512 0.32343359 0.86021336 0.89476648 0.08900515 0.23743421
  0.10750713 0.15707503 0.95771492 0.5555275 ]
 [0.06011956 0.85896329 0.86865049 0.11836881 0.73611022 0.6746362
  0.53293414 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [70]:
mean_vec = np.random.rand(30)
print(mean_vec)
mean = np.mean(mean_vec,axis=0)
mean

[0.15747287 0.40505789 0.91508092 0.1904759  0.64539228 0.87449004
 0.15119035 0.32539068 0.88011293 0.01843775 0.08848474 0.80487937
 0.89083416 0.77434993 0.48282662 0.28855837 0.02019528 0.77104269
 0.76756266 0.74771712 0.68261571 0.87969897 0.53093613 0.04871704
 0.86955264 0.60411218 0.37577754 0.3176828  0.16113628 0.27967916]


0.4983153669145063

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [79]:
ones_zeros = np.ones((5,5))
zeros = np.zeros((3,3))
print(ones_zeros)
print(zeros)
ones_zeros[1:-1,1:-1] = zeros
ones_zeros

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [82]:
zero_2 = np.zeros((7,7))
zero_2[1:-1,1:-1] = ones_zeros
zero_2

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

## False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [91]:
arr_5 = np.zeros((5,5))
temp_arr = np.arange(1,5)
#print(arr_5)
temp_arr
arr_5[[1,2,3,4],[0,1,2,3]] = temp_arr
print(arr_5)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [100]:
#checkerboard_black = np.ones((8,8))
#print(checkerboard_black)
re = np.r_[ 4*[0,1] ]              # even-numbered rows
ro = np.r_[ 4*[1,0] ]
checkerboard = np.row_stack(4*(re, ro))
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

There are 6 matrixes 56(7*8) elements.
That means the 100th element is in the second matix as the 44th element(index x = 1).
44 // no.of raws 7 --> index y = 5
index z = 1
## 100th_index = (1, 5, 1) 


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)