# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.version.version)
print(np.__config__.show())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dilan/anaconda3/envs/Strive_School_AI_March_2021\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dilan/anaconda3/envs/Strive_School_AI_March_2021\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dilan/anaconda3/envs/Strive_School_AI_March_2021\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dilan/anaconda3/envs/Strive_School_AI_March_2021\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dilan/anaconda3/envs/Strive_School_AI_March_2021\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dilan/anaconda3/envs/Strive_School_AI_March_2021\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dilan/anaco

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.zeros(10, dtype='int8')
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
a.nbytes

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
b = a.copy()
b[4] = 1
b

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8)

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
np.arange(11,50)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [7]:
to_rvrs = np.array([1,2,3,4,5])
to_rvrs = to_rvrs[::-1]
to_rvrs

array([5, 4, 3, 2, 1])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
a_vec = np.arange(0,9)
a_mat = a_vec.reshape((3,3))
print(a_vec)
a_mat

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [9]:
find_zero = np.array([1,2,0,0,4,0])
non_zero = find_zero != 0
non_zero

array([ True,  True, False, False,  True, False])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
np.random.randint(10,size =(3,3,3))

array([[[7, 9, 7],
        [3, 5, 0],
        [7, 0, 9]],

       [[9, 7, 6],
        [7, 4, 9],
        [2, 0, 5]],

       [[9, 2, 9],
        [5, 1, 8],
        [4, 9, 3]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
min_max_arr = np.random.rand(10,10)
print(min_max_arr)
print(min_max_arr.min())
print(min_max_arr.max())

[[0.45105828 0.91283143 0.12912822 0.80108014 0.94913218 0.60117835
  0.93984517 0.30340001 0.56038409 0.95429662]
 [0.25589794 0.21223577 0.35736642 0.17965739 0.34023436 0.82893667
  0.50004798 0.04476291 0.14712728 0.28650146]
 [0.18004956 0.77101037 0.34904598 0.59724903 0.55625322 0.18325209
  0.1026613  0.99518136 0.14294738 0.6257897 ]
 [0.22252862 0.9148665  0.63399714 0.7558393  0.50604056 0.19396703
  0.92057515 0.67818079 0.38874583 0.58002441]
 [0.92937566 0.8825508  0.02360694 0.52918638 0.82973514 0.28035446
  0.2176677  0.41413006 0.68672133 0.45219399]
 [0.82655758 0.11664601 0.32768734 0.82079186 0.11089773 0.87697669
  0.91354995 0.95721813 0.70812227 0.51261905]
 [0.95037877 0.76923902 0.44807195 0.19944838 0.34517856 0.82491726
  0.35181892 0.8290996  0.15050866 0.82643653]
 [0.70935047 0.14664858 0.51050671 0.4524666  0.61430725 0.38765086
  0.21579483 0.94921448 0.72107264 0.06677651]
 [0.1386691  0.20192062 0.35095428 0.57850744 0.72465174 0.17722567
  0.33030823

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
mean_vec = np.random.rand(30)
print(mean_vec)
mean = np.mean(mean_vec,axis=0)
mean

[0.48864403 0.38714491 0.47792423 0.55902941 0.35337752 0.19579803
 0.64285547 0.69337758 0.93611736 0.07118739 0.40162958 0.42596152
 0.36176485 0.32040208 0.28843629 0.34067662 0.94319351 0.11370289
 0.89334361 0.09998875 0.4762633  0.83362371 0.58919566 0.50951066
 0.59544107 0.13882206 0.12615908 0.23573212 0.07307297 0.40995751]


0.43274445986170795

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
ones_zeros = np.ones((5,5))
zeros = np.zeros((3,3))
print(ones_zeros)
print(zeros)
ones_zeros[1:-1,1:-1] = zeros
ones_zeros

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [15]:
zero_2 = np.zeros((7,7))
zero_2[1:-1,1:-1] = ones_zeros
zero_2

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

### False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [16]:
arr_5 = np.zeros((5,5))
temp_arr = np.arange(1,5)
#print(arr_5)
temp_arr
arr_5[[1,2,3,4],[0,1,2,3]] = temp_arr
print(arr_5)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [17]:
re = np.r_[ 4*[0,1] ]              
ro = np.r_[ 4*[1,0] ]
checkerboard = np.row_stack(4*(re, ro))
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

There are 6 matrixes 56(7*8) elements.
That means the 100th element is in the second matix as the 44th element(index x = 1).
44 // no.of raws 7 --> index y = 5
index z = 1
## 100th_index = (1, 5, 1) 


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [18]:
def normalized_raws(x):
    x_norm = np.linalg.norm(x, ord = 2, axis = 1, keepdims = True)
    x = x/x_norm
    return x

abnormal = np.random.rand(5,5)	
print(normalized_raws(abnormal))

[[0.41218119 0.22442616 0.26127218 0.59448562 0.59838387]
 [0.63963213 0.185202   0.69661104 0.19357017 0.18394183]
 [0.35945065 0.05899462 0.66082064 0.47590547 0.451824  ]
 [0.64291522 0.07681042 0.38312062 0.64759574 0.1208244 ]
 [0.51666003 0.24464336 0.45480119 0.51822418 0.44476018]]
