In [ ]:
# Import the needed libraries

In [ ]:
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [4]:
min_max_arr = np.random.rand(10,10)
print(min_max_arr)
print(min_max_arr.min())
print(min_max_arr.max())

[[5.66982427e-01 7.26363450e-01 8.19611685e-01 1.67420414e-01
  4.29028330e-02 7.97220132e-01 7.27920866e-02 6.50847137e-01
  7.95110605e-01 1.87909805e-01]
 [3.52578737e-01 5.65008233e-01 9.60136820e-01 8.47821218e-01
  5.30787030e-01 4.94416050e-01 6.12843998e-01 9.53579682e-02
  2.36225252e-01 8.18505190e-02]
 [4.66093863e-02 3.55430940e-01 4.43682533e-01 8.50738889e-01
  6.54966069e-01 1.71866500e-01 8.20034266e-01 3.10146277e-01
  9.33782944e-01 6.63427888e-01]
 [2.55474994e-01 4.42856748e-01 1.89483856e-01 2.37971734e-01
  6.32287587e-01 8.85733156e-01 3.51063156e-01 8.59096211e-01
  6.62638381e-01 1.76294494e-01]
 [6.94833967e-01 1.73360559e-01 3.16472388e-01 4.40432230e-01
  1.40519137e-01 6.79715298e-01 5.20613582e-01 8.84940843e-02
  1.60010849e-01 1.91178962e-01]
 [2.29115548e-01 8.34822250e-02 2.84494322e-01 7.54337537e-04
  8.57889456e-02 7.43780872e-01 7.54248087e-01 7.94968096e-01
  1.07520841e-01 4.80925554e-01]
 [2.52027511e-01 2.97735617e-01 5.58842626e-01 5.48925275e

**15. Create a 2d array with 1 on the border and 0 inside**

In [3]:
ones_zeros = np.ones((5,5))
zeros = np.zeros((3,3))
print(ones_zeros)
print(zeros)
ones_zeros[1:-1,1:-1] = zeros
ones_zeros

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])