In [21]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [12]:
arr_to_swap = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_to_swap)
arr_to_swap[[0,1]] = arr_to_swap[[1,0]]
arr_to_swap

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

**75. How to compute averages using a sliding window over an array?**

In [34]:
arr_mean = np.arange(1,21)
print(arr_mean)
indexer = np.arange(6)[None, :] + 2*np.arange(8)[:, None]
print(indexer)
arr_mean[indexer]
np.mean(arr_mean[indexer], axis= 1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 0  1  2  3  4  5]
 [ 2  3  4  5  6  7]
 [ 4  5  6  7  8  9]
 [ 6  7  8  9 10 11]
 [ 8  9 10 11 12 13]
 [10 11 12 13 14 15]
 [12 13 14 15 16 17]
 [14 15 16 17 18 19]]


array([ 3.5,  5.5,  7.5,  9.5, 11.5, 13.5, 15.5, 17.5])